name: Build and putsh image when new tag

on:
  push:
    tags: ['*']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-multiple-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USER }}/kubectl
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
            type=raw,value=alpine
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: |
            linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=alpine
            KUBECTL_VERSION=${{ github.ref_name }}
          platforms: |
            linux/amd64,linux/arm64
